import type { PulseMarket, PulseLeaderEntry } from "@/types/pulse";

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function hoursFromNow(hours: number): string {
  const d = new Date();
  d.setHours(d.getHours() + hours);
  return d.toISOString();
}

function minutesFromNow(minutes: number): string {
  const d = new Date();
  d.setMinutes(d.getMinutes() + minutes);
  return d.toISOString();
}

export const seedMarkets: PulseMarket[] = [
  // ── CRYPTO ─────────────────────────────────────────────────────────────────
  {
    id: "pulse-m1",
    title: "Will Bitcoin close above $110,000 this week?",
    description: "Based on Coinbase closing price at end of Sunday UTC.",
    category: "crypto",
    closesAt: daysFromNow(3),
    resolvesAt: daysFromNow(4),
    outcome: null,
    yesPool: 3840,
    noPool: 2160,
    status: "open",
    featured: true,
    aiGenerated: false,
    totalBettors: 284,
  },
  {
    id: "pulse-m2",
    title: "Will ETH/BTC ratio cross 0.04 before July 2026?",
    description: "Measured on Binance spot at any point before July 1 UTC.",
    category: "crypto",
    closesAt: daysFromNow(22),
    resolvesAt: daysFromNow(23),
    outcome: null,
    yesPool: 1240,
    noPool: 960,
    status: "open",
    aiGenerated: true,
    totalBettors: 118,
  },
  {
    id: "pulse-m3",
    title: "Will WLD token reach $5 before August 2026?",
    description: "Any exchange price, sustained for 10+ minutes.",
    category: "crypto",
    closesAt: daysFromNow(55),
    resolvesAt: daysFromNow(56),
    outcome: null,
    yesPool: 2100,
    noPool: 3400,
    status: "open",
    totalBettors: 321,
  },
  {
    id: "pulse-m13",
    title: "Will Solana flip Ethereum in market cap before 2027?",
    description: "SOL market cap exceeds ETH market cap per CoinGecko at any moment.",
    category: "crypto",
    closesAt: daysFromNow(180),
    resolvesAt: daysFromNow(182),
    outcome: null,
    yesPool: 1900,
    noPool: 4800,
    status: "open",
    aiGenerated: true,
    totalBettors: 412,
  },
  {
    id: "pulse-m14",
    title: "Will a spot Bitcoin ETF in Europe launch before September 2026?",
    description: "Regulated ETF listed on a major European exchange (LSE, Euronext, etc.).",
    category: "crypto",
    closesAt: daysFromNow(80),
    resolvesAt: daysFromNow(82),
    outcome: null,
    yesPool: 2800,
    noPool: 1600,
    status: "open",
    aiGenerated: false,
    totalBettors: 198,
  },
  {
    id: "pulse-m15",
    title: "Will BTC dominance stay above 55% through June 2026?",
    description: "CoinMarketCap BTC dominance must stay above 55% every day through June 30.",
    category: "crypto",
    closesAt: daysFromNow(24),
    resolvesAt: daysFromNow(25),
    outcome: null,
    yesPool: 3100,
    noPool: 1400,
    status: "open",
    aiGenerated: true,
    totalBettors: 267,
  },

  // ── SPORTS ─────────────────────────────────────────────────────────────────
  {
    id: "pulse-m4",
    title: "Will Real Madrid win the 2025-26 Champions League?",
    description: "Resolved at the final whistle of the UCL Final.",
    category: "sports",
    closesAt: daysFromNow(18),
    resolvesAt: daysFromNow(19),
    outcome: null,
    yesPool: 5600,
    noPool: 4200,
    status: "open",
    totalBettors: 562,
  },
  {
    id: "pulse-m12",
    title: "Will LeBron James announce retirement before January 2027?",
    description: "Official statement from player, team, or NBA.",
    category: "sports",
    closesAt: daysFromNow(210),
    resolvesAt: daysFromNow(212),
    outcome: null,
    yesPool: 1900,
    noPool: 3100,
    status: "open",
    totalBettors: 276,
  },
  {
    id: "pulse-m16",
    title: "Will Kylian Mbappe score 30+ goals in his debut Real Madrid season?",
    description: "All competitions combined. Tally per official Real Madrid stats.",
    category: "sports",
    closesAt: daysFromNow(40),
    resolvesAt: daysFromNow(41),
    outcome: null,
    yesPool: 4200,
    noPool: 2100,
    status: "open",
    aiGenerated: false,
    totalBettors: 489,
  },
  {
    id: "pulse-m17",
    title: "Will the 2026 FIFA World Cup final be a rematch of 2022?",
    description: "Argentina vs France in the final. Resolved at draw ceremony or final.",
    category: "sports",
    closesAt: daysFromNow(25),
    resolvesAt: daysFromNow(26),
    outcome: null,
    yesPool: 1100,
    noPool: 5800,
    status: "open",
    aiGenerated: true,
    totalBettors: 634,
  },
  {
    id: "pulse-m18",
    title: "Will any team break the NBA scoring record this season?",
    description: "Regular season points-per-game record (>125.9 PPG) per NBA.com.",
    category: "sports",
    closesAt: daysFromNow(60),
    resolvesAt: daysFromNow(61),
    outcome: null,
    yesPool: 800,
    noPool: 3200,
    status: "open",
    aiGenerated: true,
    totalBettors: 143,
  },

  // ── WORLD EVENTS ───────────────────────────────────────────────────────────
  {
    id: "pulse-m5",
    title: "Will a new country adopt Bitcoin as legal tender in 2026?",
    description: "Must be a UN-recognized nation passing formal legislation.",
    category: "world",
    closesAt: daysFromNow(180),
    resolvesAt: daysFromNow(182),
    outcome: null,
    yesPool: 1800,
    noPool: 5200,
    status: "open",
    aiGenerated: true,
    totalBettors: 447,
  },
  {
    id: "pulse-m6",
    title: "Will the US Federal Reserve cut rates in July 2026?",
    description: "Any rate cut announced at the July FOMC meeting.",
    category: "world",
    closesAt: daysFromNow(25),
    resolvesAt: daysFromNow(26),
    outcome: null,
    yesPool: 4400,
    noPool: 2600,
    status: "open",
    aiGenerated: true,
    totalBettors: 398,
  },
  {
    id: "pulse-m11",
    title: "Will World App reach 15 million users by end of 2026?",
    description: "Total registered World App users per official Worldcoin announcement.",
    category: "world",
    closesAt: daysFromNow(200),
    resolvesAt: daysFromNow(202),
    outcome: null,
    yesPool: 6800,
    noPool: 2200,
    status: "open",
    aiGenerated: false,
    totalBettors: 782,
  },
  {
    id: "pulse-m19",
    title: "Will the UN pass a binding AI governance resolution in 2026?",
    description: "A formal, legally binding resolution on AI — not just a declaration.",
    category: "world",
    closesAt: daysFromNow(150),
    resolvesAt: daysFromNow(152),
    outcome: null,
    yesPool: 1600,
    noPool: 4200,
    status: "open",
    aiGenerated: true,
    totalBettors: 289,
  },
  {
    id: "pulse-m20",
    title: "Will global inflation fall below 3% by Q4 2026?",
    description: "IMF Global Inflation Rate report for Q3 2026 (published October).",
    category: "world",
    closesAt: daysFromNow(140),
    resolvesAt: daysFromNow(142),
    outcome: null,
    yesPool: 2900,
    noPool: 2100,
    status: "open",
    aiGenerated: false,
    totalBettors: 356,
  },
  {
    id: "pulse-m21",
    title: "Will Elon Musk leave any government role before July 2026?",
    description: "Official resignation from any US government advisory or appointed role.",
    category: "world",
    closesAt: daysFromNow(20),
    resolvesAt: daysFromNow(21),
    outcome: null,
    yesPool: 5100,
    noPool: 3300,
    status: "open",
    aiGenerated: true,
    totalBettors: 721,
  },

  // ── CULTURE & TECH ─────────────────────────────────────────────────────────
  {
    id: "pulse-m7",
    title: "Will a World App mini app reach 1M daily users before September?",
    description: "Any single mini app, verified by World team public data.",
    category: "culture",
    closesAt: daysFromNow(70),
    resolvesAt: daysFromNow(72),
    outcome: null,
    yesPool: 3200,
    noPool: 1800,
    status: "open",
    totalBettors: 234,
  },
  {
    id: "pulse-m8",
    title: "Will an AI-generated song top the Billboard Hot 100 in 2026?",
    description: "Must be publicly disclosed as AI-generated by the artist or label.",
    category: "culture",
    closesAt: daysFromNow(180),
    resolvesAt: daysFromNow(182),
    outcome: null,
    yesPool: 2700,
    noPool: 4100,
    status: "open",
    aiGenerated: true,
    totalBettors: 519,
  },
  {
    id: "pulse-m22",
    title: "Will GPT-5 be publicly released before August 2026?",
    description: "OpenAI makes GPT-5 available to the public (free or paid tier).",
    category: "culture",
    closesAt: daysFromNow(60),
    resolvesAt: daysFromNow(61),
    outcome: null,
    yesPool: 4800,
    noPool: 2200,
    status: "open",
    aiGenerated: false,
    totalBettors: 876,
  },
  {
    id: "pulse-m23",
    title: "Will Apple release an AI model that beats GPT-4o on any benchmark?",
    description: "Official Apple model, any publicly available benchmark comparison.",
    category: "culture",
    closesAt: daysFromNow(90),
    resolvesAt: daysFromNow(91),
    outcome: null,
    yesPool: 1400,
    noPool: 3600,
    status: "open",
    aiGenerated: true,
    totalBettors: 311,
  },
  {
    id: "pulse-m24",
    title: "Will Tesla Full Self-Driving reach Level 4 autonomy by end of 2026?",
    description: "Official Level 4 NHTSA classification or equivalent international standard.",
    category: "culture",
    closesAt: daysFromNow(200),
    resolvesAt: daysFromNow(202),
    outcome: null,
    yesPool: 900,
    noPool: 5100,
    status: "open",
    aiGenerated: true,
    totalBettors: 428,
  },
  {
    id: "pulse-m25",
    title: "Will TikTok be banned in the US before July 2026?",
    description: "Functional TikTok app unavailable on US App Store or Google Play.",
    category: "culture",
    closesAt: daysFromNow(20),
    resolvesAt: daysFromNow(21),
    outcome: null,
    yesPool: 2100,
    noPool: 4400,
    status: "open",
    aiGenerated: false,
    totalBettors: 659,
  },

  // ── MICRO / FLASH ──────────────────────────────────────────────────────────
  {
    id: "pulse-m9",
    title: "Will BTC move more than 0.5% in the next 15 minutes?",
    description: "Measured on Binance BTCUSDT from market open time.",
    category: "micro",
    closesAt: minutesFromNow(13),
    resolvesAt: minutesFromNow(15),
    outcome: null,
    yesPool: 340,
    noPool: 410,
    status: "open",
    totalBettors: 89,
  },
  {
    id: "pulse-m10",
    title: "Will ETH gas fees exceed 15 gwei in the next hour?",
    description: "Average gas price on Ethereum mainnet.",
    category: "micro",
    closesAt: hoursFromNow(1),
    resolvesAt: hoursFromNow(1),
    outcome: null,
    yesPool: 620,
    noPool: 480,
    status: "open",
    totalBettors: 143,
  },
  {
    id: "pulse-m26",
    title: "Will BTC be green (up) vs yesterday's close in 4 hours?",
    description: "BTC/USDT on Binance. Compared to previous UTC midnight close.",
    category: "micro",
    closesAt: hoursFromNow(4),
    resolvesAt: hoursFromNow(4),
    outcome: null,
    yesPool: 980,
    noPool: 720,
    status: "open",
    totalBettors: 211,
  },
  {
    id: "pulse-m27",
    title: "Will WLD price rise more than 1% in the next 2 hours?",
    description: "Measured on Binance WLD/USDT from post time.",
    category: "micro",
    closesAt: hoursFromNow(2),
    resolvesAt: hoursFromNow(2),
    outcome: null,
    yesPool: 450,
    noPool: 630,
    status: "open",
    aiGenerated: true,
    totalBettors: 97,
  },
  {
    id: "pulse-m28",
    title: "Will any top-10 coin by market cap be up >3% today?",
    description: "24h change on CoinGecko top-10 at UTC midnight vs UTC midnight.",
    category: "micro",
    closesAt: hoursFromNow(6),
    resolvesAt: hoursFromNow(7),
    outcome: null,
    yesPool: 1100,
    noPool: 640,
    status: "open",
    aiGenerated: false,
    totalBettors: 178,
  },

  // ── PULSE EXCLUSIVE (World ID community-specific) ──────────────────────────
  {
    id: "pulse-m29",
    title: "Will PULSE hit 10,000 verified forecasters this month?",
    description: "Unique World ID nullifiers that have placed at least 1 bet.",
    category: "world",
    closesAt: daysFromNow(24),
    resolvesAt: daysFromNow(25),
    outcome: null,
    yesPool: 2400,
    noPool: 900,
    status: "open",
    aiGenerated: false,
    featured: false,
    totalBettors: 347,
  },
  {
    id: "pulse-m30",
    title: "Will Worldcoin announce a new country partnership in June 2026?",
    description: "Official Worldcoin or Tools for Humanity press release or blog post.",
    category: "world",
    closesAt: daysFromNow(24),
    resolvesAt: daysFromNow(25),
    outcome: null,
    yesPool: 3600,
    noPool: 1200,
    status: "open",
    aiGenerated: false,
    totalBettors: 531,
  },
  {
    id: "pulse-m31",
    title: "Will the World ID app add a new biometric scan type before 2027?",
    description: "Any new biometric (voice, fingerprint, face) beyond iris scan — official announcement.",
    category: "world",
    closesAt: daysFromNow(200),
    resolvesAt: daysFromNow(202),
    outcome: null,
    yesPool: 1700,
    noPool: 2900,
    status: "open",
    aiGenerated: true,
    totalBettors: 224,
  },
];

export const seedLeaderboard: PulseLeaderEntry[] = [
  { rank: 1,  username: "@oracle_signal",   initial: "O", winRate: 94, totalBets: 186, totalWonWld: 2840, streak: 22, specialty: "Crypto",  badge: "🏆" },
  { rank: 2,  username: "@signal_seven",    initial: "S", winRate: 87, totalBets: 241, totalWonWld: 1970, streak: 14, specialty: "World",   badge: "🥈" },
  { rank: 3,  username: "@forecast_mind",   initial: "F", winRate: 83, totalBets: 128, totalWonWld: 1540, streak: 9,  specialty: "Sports",  badge: "🥉" },
  { rank: 4,  username: "@chain_prophet",   initial: "C", winRate: 79, totalBets: 312, totalWonWld: 1280, streak: 7,  specialty: "Crypto"  },
  { rank: 5,  username: "@true_north_w",    initial: "T", winRate: 76, totalBets: 94,  totalWonWld: 980,  streak: 11, specialty: "Culture" },
  { rank: 6,  username: "@market_vision",   initial: "M", winRate: 74, totalBets: 156, totalWonWld: 860,  streak: 5,  specialty: "World"   },
  { rank: 7,  username: "@deep_read_x",     initial: "D", winRate: 71, totalBets: 87,  totalWonWld: 720,  streak: 3,  specialty: "Sports"  },
  { rank: 8,  username: "@verified_sage",   initial: "V", winRate: 68, totalBets: 203, totalWonWld: 590,  streak: 6,  specialty: "Micro"   },
  { rank: 9,  username: "@pulse_reader",    initial: "P", winRate: 65, totalBets: 74,  totalWonWld: 440,  streak: 2,  specialty: "Crypto"  },
  { rank: 10, username: "@world_eye",       initial: "W", winRate: 62, totalBets: 118, totalWonWld: 310,  streak: 4,  specialty: "World"   },
];

// ── Streak multiplier table ────────────────────────────────────────────────────
// Applied to payout for players on a win streak.
// Provides a bonus incentive to keep predicting accurately.
export const STREAK_MULTIPLIERS: { minStreak: number; multiplier: number; label: string }[] = [
  { minStreak: 20, multiplier: 1.5,  label: "🔥 LEGENDARY" },
  { minStreak: 10, multiplier: 1.25, label: "⚡ HOT STREAK" },
  { minStreak: 5,  multiplier: 1.1,  label: "✨ ON FIRE"   },
  { minStreak: 0,  multiplier: 1.0,  label: ""             },
];

export function getStreakMultiplier(streak: number): { multiplier: number; label: string } {
  for (const tier of STREAK_MULTIPLIERS) {
    if (streak >= tier.minStreak) return { multiplier: tier.multiplier, label: tier.label };
  }
  return { multiplier: 1.0, label: "" };
}

// ── Platform fee constants ─────────────────────────────────────────────────────
export const PLATFORM_FEE_BPS = 30;       // 0.30% on standard bets
export const CLASH_RAKE_BPS   = 1000;     // 10.0% on 1v1 Clash
export const FLASH_FEE_BPS    = 50;       // 0.50% on micro/flash markets
