import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — VeRdex",
  description: "VeRdex Privacy Policy. Learn how we collect, use, and protect your data on the VeRdex Human Prediction Network.",
  robots: { index: true, follow: true },
};

const EFFECTIVE_DATE = "July 7, 2025";
const CONTACT_EMAIL  = "brianokindo2022@gmail.com";

export default function PrivacyPage() {
  return (
    <main style={{
      minHeight: "100vh",
      background: "#07091a",
      color: "#e8eaf6",
      fontFamily: "system-ui, -apple-system, sans-serif",
      padding: "0 0 80px",
    }}>
      {/* Header */}
      <div style={{
        background: "linear-gradient(135deg, #1a1440 0%, #07091a 100%)",
        borderBottom: "1px solid rgba(99,102,241,0.2)",
        padding: "32px 24px 24px",
      }}>
        <Link href="/" style={{ color: "#6366f1", textDecoration: "none", fontSize: "0.85rem", letterSpacing: "0.05em" }}>
          ← Back to VeRdex
        </Link>
        <h1 style={{ fontSize: "1.8rem", fontWeight: 900, margin: "16px 0 4px", letterSpacing: "-0.02em" }}>
          Privacy Policy
        </h1>
        <p style={{ color: "rgba(232,234,246,0.5)", fontSize: "0.85rem", margin: 0 }}>
          Effective {EFFECTIVE_DATE} · VeRdex Human Prediction Network
        </p>
      </div>

      {/* Body */}
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "32px 24px" }}>

        <Section title="1. Overview">
          VeRdex (&quot;we&quot;, &quot;our&quot;, &quot;the Service&quot;) is a World App mini app prediction market.
          This Privacy Policy explains what data we collect, how we use it, and your rights.
          VeRdex is designed with privacy-first principles: we never collect names, email addresses,
          phone numbers, or government IDs. Identity is verified entirely through World ID — a privacy-preserving
          proof-of-personhood protocol.
        </Section>

        <Section title="2. Data We Collect">
          <strong style={{ color: "#e8eaf6" }}>2a. Data you provide</strong>
          <ul>
            <li><strong>World ID nullifier</strong>: A unique, anonymous, per-app cryptographic identifier generated by World ID. It cannot be used to identify you outside of VeRdex and is not linked to your biometrics or real identity.</li>
            <li><strong>Username</strong>: An optional display name you choose inside VeRdex. We use your World App username if you have one. Not required to use the Service.</li>
            <li><strong>Wallet address</strong>: Your World App wallet address on World Chain, used solely to send WLD payouts to you.</li>
          </ul>

          <strong style={{ color: "#e8eaf6" }}>2b. Data we generate automatically</strong>
          <ul>
            <li><strong>Bet records</strong>: Market ID, position (YES/NO), WLD stake amount, on-chain transaction reference, timestamp, outcome.</li>
            <li><strong>Leaderboard stats</strong>: Aggregate win/loss record, total wagered, win streak, specialty category. These are public.</li>
            <li><strong>Referral links</strong>: If you refer someone, we record that relationship by nullifier.</li>
            <li><strong>Server logs</strong>: Standard request logs (IP address, user agent, timestamp) retained for up to 30 days for security and debugging.</li>
          </ul>

          <strong style={{ color: "#e8eaf6" }}>2c. What we do NOT collect</strong>
          <ul>
            <li>Real name, email, phone number, or government ID</li>
            <li>Biometric data (this is handled exclusively by World and never shared with us)</li>
            <li>Location data beyond IP-derived country (used only for rate-limiting)</li>
            <li>Social media accounts or browsing history</li>
          </ul>
        </Section>

        <Section title="3. How We Use Your Data">
          <ul>
            <li>To verify you are a unique World ID human and prevent multi-accounting</li>
            <li>To record and settle your bets and payouts accurately</li>
            <li>To display leaderboards and your personal stats</li>
            <li>To process referral rewards</li>
            <li>To send you push notifications within World App about market resolutions and payouts (opt-out by disabling notifications in World App settings)</li>
            <li>To detect and prevent fraud, abuse, and security incidents</li>
            <li>To improve the Service through aggregate, anonymized analytics</li>
          </ul>
          We do not sell your data. We do not use your data for advertising.
        </Section>

        <Section title="4. Data Sharing and Third Parties">
          We share data with third parties only as necessary to operate the Service:
          <ul>
            <li>
              <strong>Supabase</strong> — our database provider. Bet records, player stats, and market data are stored in Supabase (EU/US regions). Supabase is SOC 2 certified.
              <a href="https://supabase.com/privacy" style={{ color: "#6366f1", marginLeft: 4 }}>Privacy Policy ↗</a>
            </li>
            <li>
              <strong>World / Worldcoin</strong> — World ID verification and World App wallet infrastructure. Your World ID nullifier is generated by World and shared with us only after you consent.
              <a href="https://world.org/privacy" style={{ color: "#6366f1", marginLeft: 4 }}>Privacy Policy ↗</a>
            </li>
            <li>
              <strong>Vercel</strong> — our hosting and serverless compute provider.
              <a href="https://vercel.com/legal/privacy-policy" style={{ color: "#6366f1", marginLeft: 4 }}>Privacy Policy ↗</a>
            </li>
            <li>
              <strong>Anthropic</strong> — AI oracle market generation (Claude). Market generation prompts contain no personal data. We use a zero-data-retention API configuration.
              <a href="https://www.anthropic.com/legal/privacy" style={{ color: "#6366f1", marginLeft: 4 }}>Privacy Policy ↗</a>
            </li>
            <li>
              <strong>Public blockchain</strong> — WLD transactions are recorded on World Chain, a public blockchain. On-chain data (wallet addresses, tx hashes, amounts) is publicly visible.
            </li>
          </ul>
          We do not share your data with advertisers, data brokers, or analytics platforms that track you across sites.
        </Section>

        <Section title="5. Data Retention">
          <ul>
            <li>Bet records and payout history: retained indefinitely (required for audit and dispute resolution)</li>
            <li>Player stats and leaderboard data: retained indefinitely (users can request deletion — see Section 7)</li>
            <li>Server request logs: 30 days</li>
            <li>Rate-limit buckets: in-memory, reset every 60 seconds</li>
          </ul>
        </Section>

        <Section title="6. Security">
          We take data security seriously:
          <ul>
            <li>All API endpoints require World ID verification or a signed cron secret for internal operations</li>
            <li>Supabase Row-Level Security (RLS) ensures bet and payout data is never exposed to unauthenticated queries</li>
            <li>All data in transit is encrypted via TLS 1.2+</li>
            <li>Treasury private keys are stored in environment secrets, never in code</li>
            <li>Security headers (CSP, X-Frame-Options, Permissions-Policy) are applied on all responses</li>
          </ul>
          No security system is perfect. If you discover a security vulnerability, please disclose it responsibly to{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#6366f1" }}>{CONTACT_EMAIL}</a>.
        </Section>

        <Section title="7. Your Rights">
          You have the right to:
          <ul>
            <li><strong>Access</strong>: Request a copy of the data we hold associated with your World ID nullifier</li>
            <li><strong>Deletion</strong>: Request deletion of your account data. Note: on-chain transactions cannot be deleted as they are recorded on a public blockchain. Bet records required for open disputes will be retained until resolution.</li>
            <li><strong>Correction</strong>: Request correction of inaccurate data (e.g., username)</li>
            <li><strong>Opt-out of notifications</strong>: Disable push notifications via World App settings at any time</li>
          </ul>
          To exercise any right, email us at{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#6366f1" }}>{CONTACT_EMAIL}</a>{" "}
          with your World ID nullifier (visible in VeRdex settings).
        </Section>

        <Section title="8. Children's Privacy">
          VeRdex is not directed at or intended for use by persons under 18 years of age.
          We do not knowingly collect data from minors. If you believe a minor has used the Service,
          contact us immediately.
        </Section>

        <Section title="9. Changes to This Policy">
          We may update this Privacy Policy from time to time. We will post changes at this URL with a
          new effective date. Material changes will be communicated via World App push notification when
          possible. Continued use after changes are posted constitutes acceptance.
        </Section>

        <Section title="10. Contact">
          For privacy inquiries, data access requests, or security disclosures:{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#6366f1" }}>{CONTACT_EMAIL}</a>
        </Section>

        <div style={{ borderTop: "1px solid rgba(99,102,241,0.15)", paddingTop: 24, marginTop: 32, fontSize: "0.8rem", color: "rgba(232,234,246,0.4)" }}>
          <Link href="/terms" style={{ color: "#6366f1", marginRight: 16 }}>Terms of Service</Link>
          <Link href="/" style={{ color: "#6366f1" }}>Back to VeRdex</Link>
        </div>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 32 }}>
      <h2 style={{
        fontSize: "1rem",
        fontWeight: 700,
        color: "#6366f1",
        margin: "0 0 10px",
        letterSpacing: "0.02em",
      }}>
        {title}
      </h2>
      <div style={{ fontSize: "0.9rem", lineHeight: 1.7, color: "rgba(232,234,246,0.85)" }}>
        {children}
      </div>
    </section>
  );
}
